[package]
name = "ftw"
version = "0.1.0"
authors = ["Michael Angelo Calimlim <macalimlim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-edit = "0.7.0"
clap = "3.0.0-beta.2"
fs_extra = "1.2.0"
liquid = "0.21.4"
liquid-core = "0.21.2"
thiserror = "1.0.23"
voca_rs = "1.13.0"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"
